// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Patrol360.Infrastructure.Persistence;

#nullable disable

namespace Patrol360.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(Patrol360DbContext))]
    [Migration("20260520090720_InventoryCatalogItemDetails")]
    partial class InventoryCatalogItemDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.AssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<long>("LockVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("lock_version");

                    b.Property<Guid>("PatrolRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("patrol_request_id");

                    b.Property<DateTimeOffset>("PlannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_at");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("shift");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PatrolRequestId")
                        .IsUnique();

                    b.HasIndex("PlannedAt")
                        .HasDatabaseName("ix_assignments_planned_at");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_assignments_route_id");

                    b.HasIndex("EmployeeId", "Status")
                        .HasDatabaseName("ix_assignments_employee_status");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.EmployeeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("department");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("full_name");

                    b.Property<bool>("HasMobileAccount")
                        .HasColumnType("boolean")
                        .HasColumnName("has_mobile_account");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("PersonnelNo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("personnel_no");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("position");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("shift");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelNo")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_personnel_no");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_employees_status");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.InventoryCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex("LegacyId")
                        .HasDatabaseName("ix_inventory_categories_legacy_id");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_categories_parent_name");

                    b.ToTable("categories", "inventory");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.InventoryItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualItemName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("actual_item_name");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("article");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("brand_name");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("ClothingSize")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("clothing_size");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DefaultLifeMonths")
                        .HasColumnType("integer")
                        .HasColumnName("default_life_months");

                    b.Property<long?>("DefaultUnitPriceMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("default_unit_price_minor");

                    b.Property<string>("GloveSize")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("glove_size");

                    b.Property<string>("HeadSize")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("head_size");

                    b.Property<string>("HeightSize")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("height_size");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_consumable");

                    b.Property<string>("ItemKind")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("item_kind");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<decimal?>("MinStockQty")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("min_stock_qty");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("model_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<string>("NormItemName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("norm_item_name");

                    b.Property<string>("ProtectionClass")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("protection_class");

                    b.Property<string>("RespiratorSize")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("respirator_size");

                    b.Property<string>("ShoeSize")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("shoe_size");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("sku");

                    b.Property<bool>("TrackLife")
                        .HasColumnType("boolean")
                        .HasColumnName("track_life");

                    b.Property<string>("TrackingType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tracking_type");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_inventory_items_category_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_inventory_items_is_active");

                    b.HasIndex("LegacyId")
                        .HasDatabaseName("ix_inventory_items_legacy_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_items_name");

                    b.HasIndex("Sku")
                        .HasDatabaseName("ix_inventory_items_sku");

                    b.HasIndex("UnitId");

                    b.ToTable("items", "inventory");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.InventoryStockMoveEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<string>("MoveType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("move_type");

                    b.Property<DateTimeOffset>("MovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("moved_at");

                    b.Property<decimal>("QuantityDelta")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("qty_delta");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reference_type");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LegacyId")
                        .HasDatabaseName("ix_inventory_stock_moves_legacy_id");

                    b.HasIndex("ItemId", "MovedAt")
                        .HasDatabaseName("ix_inventory_stock_moves_item_moved");

                    b.HasIndex("WarehouseId", "MovedAt")
                        .HasDatabaseName("ix_inventory_stock_moves_warehouse_moved");

                    b.ToTable("stock_moves", "inventory");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.InventoryUnitEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("LegacyId")
                        .HasDatabaseName("ix_inventory_units_legacy_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_units_name");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_units_symbol");

                    b.ToTable("units", "inventory");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.InventoryWarehouseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LegacyId")
                        .HasDatabaseName("ix_inventory_warehouses_legacy_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_warehouses_name");

                    b.ToTable("warehouses", "inventory");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.MobileAccountAuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("details");

                    b.Property<Guid>("MobileAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("mobile_account_id");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_mobile_account_audit_action");

                    b.HasIndex("MobileAccountId", "CreatedAt")
                        .HasDatabaseName("ix_mobile_account_audit_account_created");

                    b.ToTable("mobile_account_audit_events", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.MobileAccountEmployeeBindingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DetachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detached_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("MobileAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("mobile_account_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_mobile_account_employee_bindings_employee");

                    b.HasIndex("MobileAccountId", "EmployeeId", "DetachedAt")
                        .HasDatabaseName("ix_mobile_account_employee_bindings_account_employee");

                    b.ToTable("mobile_account_employee_bindings", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.MobileAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("BoundEmployees")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("bound_employees");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("device");

                    b.Property<string>("EmployeeScope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("employee_scope");

                    b.Property<DateTimeOffset?>("LastPasswordResetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_password_reset_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PasswordResetRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("password_reset_required");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("role");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("session");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ux_mobile_accounts_login");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_mobile_accounts_status");

                    b.ToTable("mobile_accounts", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.MobileAccountSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("app_version");

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("device");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("MobileAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("mobile_account_id");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("platform");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("MobileAccountId", "LastSeenAt")
                        .HasDatabaseName("ix_mobile_account_sessions_account_seen");

                    b.ToTable("mobile_account_sessions", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.PatrolRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("description");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("employee_name");

                    b.Property<string>("NotificationText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notification_text");

                    b.Property<bool>("NotifyEmployee")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_employee");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("number");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("route_name");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<TimeOnly?>("ScheduledTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("scheduled_time");

                    b.Property<Guid?>("SourceResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_result_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ux_patrol_requests_number");

                    b.HasIndex("RouteId");

                    b.HasIndex("ScheduledDate")
                        .HasDatabaseName("ix_patrol_requests_scheduled_date");

                    b.HasIndex("SourceResultId")
                        .HasDatabaseName("ix_patrol_requests_source_result_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_patrol_requests_status");

                    b.ToTable("patrol_requests", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.PatrolResultAttachmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("PatrolResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("patrol_result_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id");

                    b.HasIndex("PatrolResultId", "CreatedAt")
                        .HasDatabaseName("ix_patrol_result_attachments_result_created");

                    b.ToTable("patrol_result_attachments", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.PatrolResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_at");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Deviation")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("deviation");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("employee_name");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("issue_type");

                    b.Property<int>("Photos")
                        .HasColumnType("integer")
                        .HasColumnName("photos");

                    b.Property<DateTimeOffset>("PlannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_at");

                    b.Property<string>("PointName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("point_name");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("route_name");

                    b.Property<Guid?>("RoutePointId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_point_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("severity");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("shift");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("status");

                    b.Property<string>("Territory")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("territory");

                    b.HasKey("Id");

                    b.HasIndex("ActualAt")
                        .HasDatabaseName("ix_patrol_results_actual_at");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_patrol_results_employee_id");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_patrol_results_route_id");

                    b.HasIndex("RoutePointId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_patrol_results_status");

                    b.ToTable("patrol_results", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.PatrolResultIssueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("message");

                    b.Property<Guid>("PatrolResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("patrol_result_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("severity");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("issue_type");

                    b.HasKey("Id");

                    b.HasIndex("PatrolResultId", "CreatedAt")
                        .HasDatabaseName("ix_patrol_result_issues_result_created");

                    b.ToTable("patrol_result_issues", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.PermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_permissions_code");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_code");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.RolePermissionEntity", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.RouteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Distance")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("distance");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("duration");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Periodicity")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("periodicity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.Property<string>("Territory")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("territory");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("ix_routes_archived");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_routes_name");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.RoutePointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExpectedTime")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("expected_time");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("interval");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("NfcCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nfc_code");

                    b.Property<bool>("RequiresPhoto")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_photo");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer")
                        .HasColumnName("seq_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tag");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("point_type");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("zone");

                    b.HasKey("Id");

                    b.HasIndex("NfcCode")
                        .HasDatabaseName("ix_route_points_nfc_code");

                    b.HasIndex("RouteId", "SequenceNo")
                        .IsUnique()
                        .HasDatabaseName("ux_route_points_route_seq");

                    b.ToTable("route_points", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.SiteUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("login");

                    b.Property<string>("NormalizedLogin")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedLogin")
                        .IsUnique()
                        .HasDatabaseName("ux_site_users_normalized_login");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_site_users_status");

                    b.ToTable("site_users", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.SiteUserRoleEntity", b =>
                {
                    b.Property<Guid>("SiteUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("SiteUserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("site_user_roles", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.SiteUserSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("SiteUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_user_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_site_user_sessions_token_hash");

                    b.HasIndex("SiteUserId", "ExpiresAt")
                        .HasDatabaseName("ix_site_user_sessions_user_expires");

                    b.ToTable("site_user_sessions", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.AssignmentEntity", b =>
                {
                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.EmployeeEntity", "Employee")
                        .WithMany("Assignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.PatrolRequestEntity", "PatrolRequest")
                        .WithOne("Assignment")
                        .HasForeignKey("Patrol360.Infrastructure.Persistence.Entities.AssignmentEntity", "PatrolRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.RouteEntity", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PatrolRequest");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.InventoryCategoryEntity", b =>
                {
                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.InventoryCategoryEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.InventoryItemEntity", b =>
                {
                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.InventoryCategoryEntity", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.InventoryUnitEntity", "Unit")
                        .WithMany("Items")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.InventoryStockMoveEntity", b =>
                {
                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.EmployeeEntity", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.InventoryItemEntity", "Item")
                        .WithMany("StockMoves")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.InventoryWarehouseEntity", "Warehouse")
                        .WithMany("StockMoves")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Item");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.MobileAccountEmployeeBindingEntity", b =>
                {
                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.EmployeeEntity", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.MobileAccountEntity", "MobileAccount")
                        .WithMany("EmployeeBindings")
                        .HasForeignKey("MobileAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("MobileAccount");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.MobileAccountSessionEntity", b =>
                {
                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.MobileAccountEntity", "MobileAccount")
                        .WithMany("Sessions")
                        .HasForeignKey("MobileAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MobileAccount");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.PatrolRequestEntity", b =>
                {
                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.EmployeeEntity", "Employee")
                        .WithMany("PatrolRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.RouteEntity", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.PatrolResultEntity", "SourceResult")
                        .WithMany()
                        .HasForeignKey("SourceResultId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("Route");

                    b.Navigation("SourceResult");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.PatrolResultAttachmentEntity", b =>
                {
                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.PatrolResultEntity", "PatrolResult")
                        .WithMany("Attachments")
                        .HasForeignKey("PatrolResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatrolResult");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.PatrolResultEntity", b =>
                {
                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.AssignmentEntity", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.EmployeeEntity", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.RouteEntity", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.RoutePointEntity", "RoutePoint")
                        .WithMany()
                        .HasForeignKey("RoutePointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assignment");

                    b.Navigation("Employee");

                    b.Navigation("Route");

                    b.Navigation("RoutePoint");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.PatrolResultIssueEntity", b =>
                {
                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.PatrolResultEntity", "PatrolResult")
                        .WithMany("Issues")
                        .HasForeignKey("PatrolResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatrolResult");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.RolePermissionEntity", b =>
                {
                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.PermissionEntity", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.RoleEntity", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.RoutePointEntity", b =>
                {
                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.RouteEntity", "Route")
                        .WithMany("Points")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.SiteUserRoleEntity", b =>
                {
                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.RoleEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.SiteUserEntity", "SiteUser")
                        .WithMany("Roles")
                        .HasForeignKey("SiteUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("SiteUser");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.SiteUserSessionEntity", b =>
                {
                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.SiteUserEntity", "SiteUser")
                        .WithMany("Sessions")
                        .HasForeignKey("SiteUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteUser");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.EmployeeEntity", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("PatrolRequests");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.InventoryCategoryEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.InventoryItemEntity", b =>
                {
                    b.Navigation("StockMoves");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.InventoryUnitEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.InventoryWarehouseEntity", b =>
                {
                    b.Navigation("StockMoves");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.MobileAccountEntity", b =>
                {
                    b.Navigation("EmployeeBindings");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.PatrolRequestEntity", b =>
                {
                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.PatrolResultEntity", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Issues");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.PermissionEntity", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.RoleEntity", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.RouteEntity", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.SiteUserEntity", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
