// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Patrol360.Infrastructure.Persistence;

#nullable disable

namespace Patrol360.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(Patrol360DbContext))]
    [Migration("20260514201028_RouteCatalogCrudFields")]
    partial class RouteCatalogCrudFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.AssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<long>("LockVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("lock_version");

                    b.Property<Guid>("PatrolRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("patrol_request_id");

                    b.Property<DateTimeOffset>("PlannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_at");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("shift");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PatrolRequestId")
                        .IsUnique();

                    b.HasIndex("PlannedAt")
                        .HasDatabaseName("ix_assignments_planned_at");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_assignments_route_id");

                    b.HasIndex("EmployeeId", "Status")
                        .HasDatabaseName("ix_assignments_employee_status");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.EmployeeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("department");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("full_name");

                    b.Property<bool>("HasMobileAccount")
                        .HasColumnType("boolean")
                        .HasColumnName("has_mobile_account");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("PersonnelNo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("personnel_no");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("position");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("shift");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelNo")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_personnel_no");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_employees_status");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.PatrolRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("description");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("employee_name");

                    b.Property<string>("NotificationText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notification_text");

                    b.Property<bool>("NotifyEmployee")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_employee");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("number");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("route_name");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<TimeOnly?>("ScheduledTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("scheduled_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ux_patrol_requests_number");

                    b.HasIndex("RouteId");

                    b.HasIndex("ScheduledDate")
                        .HasDatabaseName("ix_patrol_requests_scheduled_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_patrol_requests_status");

                    b.ToTable("patrol_requests", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.RouteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Distance")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("distance");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("duration");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Periodicity")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("periodicity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.Property<string>("Territory")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("territory");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("ix_routes_archived");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_routes_name");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.RoutePointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExpectedTime")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("expected_time");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("interval");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("NfcCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nfc_code");

                    b.Property<bool>("RequiresPhoto")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_photo");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer")
                        .HasColumnName("seq_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tag");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("point_type");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("zone");

                    b.HasKey("Id");

                    b.HasIndex("NfcCode")
                        .HasDatabaseName("ix_route_points_nfc_code");

                    b.HasIndex("RouteId", "SequenceNo")
                        .IsUnique()
                        .HasDatabaseName("ux_route_points_route_seq");

                    b.ToTable("route_points", (string)null);
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.AssignmentEntity", b =>
                {
                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.EmployeeEntity", "Employee")
                        .WithMany("Assignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.PatrolRequestEntity", "PatrolRequest")
                        .WithOne("Assignment")
                        .HasForeignKey("Patrol360.Infrastructure.Persistence.Entities.AssignmentEntity", "PatrolRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.RouteEntity", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PatrolRequest");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.PatrolRequestEntity", b =>
                {
                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.EmployeeEntity", "Employee")
                        .WithMany("PatrolRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.RouteEntity", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.RoutePointEntity", b =>
                {
                    b.HasOne("Patrol360.Infrastructure.Persistence.Entities.RouteEntity", "Route")
                        .WithMany("Points")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.EmployeeEntity", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("PatrolRequests");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.PatrolRequestEntity", b =>
                {
                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Patrol360.Infrastructure.Persistence.Entities.RouteEntity", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
