import type {
  ActivePatrol,
  Employee,
  EmployeeDirectoryItem,
  Metric,
  MobileAccount,
  PatrolResult,
  RouteDirectoryItem,
  RouteOption,
  ScheduleCell,
  ScreenConfig,
  ServiceRequest,
  SiteUser,
} from "./types";
import accountingEmployeesSeed from "./fixtures/accountingEmployees.json";

export const screens: ScreenConfig[] = [
  {
    id: "dashboard",
    label: "Дашборд",
    shortLabel: "Главное",
    hint: "сводка смены",
    title: "Детальный дашборд обходов",
    subtitle: "Онлайн-мониторинг патрулирования территории на сегодня",
    icon: "¦",
    createLabel: "Назначить",
  },
  {
    id: "results",
    label: "Результаты обходов",
    shortLabel: "Результаты",
    hint: "обходы и проблемы",
    title: "Результаты обходов",
    subtitle: "Факты прохождения точек, фото, комментарии и замечания",
    icon: "≡",
    createLabel: "Экспорт",
  },
  {
    id: "assign",
    label: "Назначения",
    shortLabel: "Назначения",
    hint: "сейчас",
    title: "Назначения",
    subtitle: "Оперативное распределение сотрудников на маршруты в реальном времени",
    icon: "+",
    createLabel: "Назначить",
  },
  {
    id: "employees",
    label: "Сотрудники",
    shortLabel: "Сотрудники",
    hint: "учет и смены",
    title: "Сотрудники",
    subtitle: "Учет, поиск, создание и управление сотрудниками",
    icon: "◎",
    createLabel: "Создать сотрудника",
  },
  {
    id: "schedule",
    label: "Плановый обход",
    shortLabel: "План",
    hint: "день / ночь",
    title: "Планирование обходов",
    subtitle: "Недельный и месячный наряд по дневным и ночным сменам",
    icon: "□",
    createLabel: "Сохранить план",
  },
  {
    id: "accounts",
    label: "Мобильные аккаунты",
    shortLabel: "Аккаунты",
    hint: "мобильный вход",
    title: "Мобильные аккаунты",
    subtitle: "Создание логинов для телефона и привязка сотрудников по ФИО",
    icon: "◉",
    createLabel: "Создать аккаунт",
  },
  {
    id: "routes",
    label: "Маршруты и точки",
    shortLabel: "Маршруты",
    hint: "точки и NFC",
    title: "Маршруты и точки",
    subtitle: "Управление маршрутами, точками контроля и NFC-метками",
    icon: "⌖",
    createLabel: "Создать маршрут",
  },
  {
    id: "users",
    label: "Управление пользователями",
    shortLabel: "Пользователи",
    hint: "web-доступ",
    title: "Управление пользователями",
    subtitle: "Настройки доступа к веб-панели: роли, права, блокировка и восстановление паролей",
    icon: "◌",
    createLabel: "Создать пользователя",
  },
  {
    id: "perco-integration",
    label: "Интеграции PERCo-Web",
    shortLabel: "PERCo-Web",
    hint: "сотрудники и проходы",
    title: "Интеграция PERCo-Web",
    subtitle: "Подключение, проверка /dev, параметры синхронизации и журнал ошибок PERCo-Web.",
    icon: "P",
    createLabel: "Проверить подключение",
  },
  {
    id: "emu-dashboard",
    label: "ЭМУ: Дашборд",
    shortLabel: "Дашборд",
    hint: "оперативная сводка",
    title: "ЭМУ: дашборд",
    subtitle: "Сводка по работам Энерго-Механического-Отдела, активным карточкам и плану недели",
    icon: "D",
    createLabel: "Обновить ЭМУ",
  },
  {
    id: "emu-work-accounting",
    label: "ЭМУ: Учет работ",
    shortLabel: "Учет работ",
    hint: "приход, пауза, завершение",
    title: "ЭМУ: учет работ",
    subtitle: "Отправка сотрудников в работу, фиксация пауз, возврата, результата и истории изменений",
    icon: "W",
    createLabel: "Отправить в работу",
  },
  {
    id: "emu-completed-work-history",
    label: "ЭМУ: История выполненных работ",
    shortLabel: "История",
    hint: "время и аудит",
    title: "ЭМУ: история выполненных работ",
    subtitle: "Просмотр выполненных работ за период, по сотрудникам, участкам и событиям карточки",
    icon: "H",
    createLabel: "Сформировать отчет",
  },
  {
    id: "inventory-overview",
    label: "Обзор учета",
    shortLabel: "Учет",
    hint: "выдачи и операции",
    title: "Бухгалтерия: обзор учета",
    subtitle: "Первый слой переноса IT-inventarizaci: выдача, СИЗ, движения и отчеты",
    icon: "I",
    createLabel: "Открыть план переноса",
  },
  {
    id: "inventory-employees",
    label: "Сотрудники учета",
    shortLabel: "Получатели",
    hint: "карточки выдачи",
    title: "Бухгалтерия: сотрудники",
    subtitle: "Получатели инвентаря, карточки выдачи и связь с общим справочником сотрудников",
    icon: "E",
    createLabel: "Сверить сотрудников",
  },
  {
    id: "inventory-items",
    label: "Номенклатура",
    shortLabel: "Позиции",
    hint: "каталог позиций",
    title: "Бухгалтерия: номенклатура",
    subtitle: "Каталог позиций, категории, единицы измерения и карточки для выдачи",
    icon: "N",
    createLabel: "Добавить позицию",
  },
  {
    id: "inventory-issue",
    label: "Выдача",
    shortLabel: "Выдача",
    hint: "сотрудникам",
    title: "Бухгалтерия: выдача",
    subtitle: "Оформление выдачи инвентаря сотрудникам и фиксация истории движения",
    icon: "V",
    createLabel: "Создать выдачу",
  },
  {
    id: "inventory-operations",
    label: "Возврат и списание",
    shortLabel: "Операции",
    hint: "возврат и списание",
    title: "Бухгалтерия: возврат и списание",
    subtitle: "Возвраты, списания и история движения предметов по сотрудникам",
    icon: "O",
    createLabel: "Создать операцию",
  },
  {
    id: "inventory-custody",
    label: "Под запись",
    shortLabel: "Под запись",
    hint: "акты и записи",
    title: "Бухгалтерия: под запись",
    subtitle: "Выдача под личную ответственность, акты, закрытие и архив",
    icon: "P",
    createLabel: "Создать акт",
  },
  {
    id: "inventory-ppe",
    label: "СИЗ",
    shortLabel: "СИЗ",
    hint: "карточки и нормы",
    title: "Бухгалтерия: СИЗ",
    subtitle: "Карточки СИЗ, нормы, строки выдачи, возвраты и печатные формы",
    icon: "S",
    createLabel: "Создать карточку СИЗ",
  },
  {
    id: "inventory-reports",
    label: "Отчеты учета",
    shortLabel: "Отчеты",
    hint: "экспорт и печать",
    title: "Бухгалтерия: отчеты",
    subtitle: "Excel/PDF/DOCX, печатные формы и сверка итоговых сумм",
    icon: "R",
    createLabel: "Сформировать отчет",
  },
  {
    id: "inventory-history",
    label: "История",
    shortLabel: "История",
    hint: "журнал операций",
    title: "Бухгалтерия: история",
    subtitle: "Единый журнал выдач, возвратов, списаний, СИЗ и записей под ответственность.",
    icon: "H",
    createLabel: "Обновить журнал",
  },
  {
    id: "inventory-users",
    label: "Права Inventory",
    shortLabel: "Права",
    hint: "RBAC",
    title: "Бухгалтерия: права Inventory",
    subtitle: "Роли и права Inventory поверх текущего RBAC Patrol360.",
    icon: "U",
    createLabel: "Открыть пользователей",
  },
  {
    id: "inventory-system-log",
    label: "Системный журнал",
    shortLabel: "Журнал",
    hint: "аудит",
    title: "Бухгалтерия: системный журнал",
    subtitle: "Аудит изменений, импортов и выгрузок Inventory.",
    icon: "L",
    createLabel: "Открыть аудит",
  },
  {
    id: "inventory-settings",
    label: "Настройки учета",
    shortLabel: "Настройки",
    hint: "нормы и справочники",
    title: "Бухгалтерия: настройки учета",
    subtitle: "Нормы, наборы номенклатуры, причины списания и справочники Inventory",
    icon: "T",
    createLabel: "Открыть настройки",
  },
];

export const dashboardMetrics: Metric[] = [];
export const activePatrols: ActivePatrol[] = [];
export const patrolResults: PatrolResult[] = [];
export const serviceRequests: ServiceRequest[] = [];
export const employees: Employee[] = [];
export const employeeDirectory: EmployeeDirectoryItem[] = accountingEmployeesSeed.map((employee) => ({
  id: employee.id,
  fullName: employee.fullName,
  initials: employee.fullName
    .split(" ")
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? "")
    .join(""),
  personnelNo: employee.personnelNo,
  position: employee.position,
  department: employee.department,
  employeeGroup: employee.employeeGroup,
  birthDate: employee.birthDate ?? "",
  zone: employee.department,
  status: "Активен" as EmployeeDirectoryItem["status"],
  routesDone: 0,
  routesTotal: 0,
  mobileStatus: "Не привязан" as EmployeeDirectoryItem["mobileStatus"],
  lastSeen: "Не входил",
  phone: "",
  hiredAt: employee.hiredAt ?? "",
  brigade: "",
  shift: "День",
  leader: "",
  email: "",
}));
export const siteUsers: SiteUser[] = [];
export const assignableRoutes: RouteOption[] = [];
export const initialAccounts: MobileAccount[] = [];
export const routeDirectory: RouteDirectoryItem[] = [];
export const scheduleCells: ScheduleCell[] = [];
export const securityEvents: string[][] = [];

export const weekDays = ["Пн 11.05", "Вт 12.05", "Ср 13.05", "Чт 14.05", "Пт 15.05", "Сб 16.05", "Вс 17.05"];
