import type {
  ActivePatrol,
  Employee,
  EmployeeDirectoryItem,
  Metric,
  MobileAccount,
  PatrolResult,
  RouteDirectoryItem,
  RouteOption,
  ScheduleCell,
  ScreenConfig,
  ServiceRequest,
  SiteUser,
} from "./types";
import accountingEmployeesSeed from "./fixtures/accountingEmployees.json";

export const screens: ScreenConfig[] = [
  {
    id: "dashboard",
    label: "Дашборд",
    shortLabel: "Главное",
    hint: "сводка смены",
    title: "Детальный дашборд обходов",
    subtitle: "Онлайн-мониторинг патрулирования территории на сегодня",
    icon: "¦",
    createLabel: "Назначить",
  },
  {
    id: "results",
    label: "Результаты обходов",
    shortLabel: "Результаты",
    hint: "обходы и проблемы",
    title: "Результаты обходов",
    subtitle: "Факты прохождения точек, фото, комментарии и замечания",
    icon: "≡",
    createLabel: "Экспорт",
  },
  {
    id: "assign",
    label: "Назначения",
    shortLabel: "Назначения",
    hint: "сейчас",
    title: "Назначения",
    subtitle: "Оперативное распределение сотрудников на маршруты в реальном времени",
    icon: "+",
    createLabel: "Назначить",
  },
  {
    id: "employees",
    label: "Сотрудники",
    shortLabel: "Сотрудники",
    hint: "учет и смены",
    title: "Сотрудники",
    subtitle: "Учет, поиск, создание и управление сотрудниками",
    icon: "◎",
    createLabel: "Создать сотрудника",
  },
  {
    id: "schedule",
    label: "Плановый обход",
    shortLabel: "План",
    hint: "день / ночь",
    title: "Планирование обходов",
    subtitle: "Недельный и месячный наряд по дневным и ночным сменам",
    icon: "□",
    createLabel: "Сохранить план",
  },
  {
    id: "accounts",
    label: "Мобильные аккаунты",
    shortLabel: "Аккаунты",
    hint: "мобильный вход",
    title: "Мобильные аккаунты",
    subtitle: "Создание логинов для телефона и привязка сотрудников по ФИО",
    icon: "◉",
    createLabel: "Создать аккаунт",
  },
  {
    id: "routes",
    label: "Маршруты и точки",
    shortLabel: "Маршруты",
    hint: "точки и NFC",
    title: "Маршруты и точки",
    subtitle: "Управление маршрутами, точками контроля и NFC-метками",
    icon: "⌖",
    createLabel: "Создать маршрут",
  },
  {
    id: "users",
    label: "Управление пользователями",
    shortLabel: "Пользователи",
    hint: "web-доступ",
    title: "Управление пользователями",
    subtitle: "Настройки доступа к веб-панели: роли, права, блокировка и восстановление паролей",
    icon: "◌",
    createLabel: "Создать пользователя",
  },
  {
    id: "perco-integration",
    label: "Интеграции PERCo-Web",
    shortLabel: "PERCo-Web",
    hint: "сотрудники и проходы",
    title: "Интеграция PERCo-Web",
    subtitle: "Подключение, проверка /dev, параметры синхронизации и журнал ошибок PERCo-Web.",
    icon: "P",
    createLabel: "Проверить подключение",
  },
  {
    id: "emu-dashboard",
    label: "ЭМУ: Дашборд",
    shortLabel: "Дашборд",
    hint: "оперативная сводка",
    title: "ЭМУ: дашборд",
    subtitle: "Сводка по работам Энерго-Механического-Отдела, активным карточкам и плану недели",
    icon: "D",
    createLabel: "Обновить ЭМУ",
  },
  {
    id: "emu-work-accounting",
    label: "ЭМУ: Учет работ",
    shortLabel: "Учет работ",
    hint: "приход, пауза, завершение",
    title: "ЭМУ: учет работ",
    subtitle: "Отправка сотрудников в работу, фиксация пауз, возврата, результата и истории изменений",
    icon: "W",
    createLabel: "Отправить в работу",
  },
  {
    id: "emu-completed-work-history",
    label: "ЭМУ: История выполненных работ",
    shortLabel: "История",
    hint: "время и аудит",
    title: "ЭМУ: история выполненных работ",
    subtitle: "Просмотр выполненных работ за период, по сотрудникам, участкам и событиям карточки",
    icon: "H",
    createLabel: "Сформировать отчет",
  },
  {
    id: "inventory-overview",
    label: "Обзор учета",
    shortLabel: "Учет",
    hint: "выдачи и операции",
    title: "Бухгалтерия: обзор учета",
    subtitle: "Первый слой переноса IT-inventarizaci: выдача, СИЗ, движения и отчеты",
    icon: "I",
    createLabel: "Открыть план переноса",
  },
  {
    id: "inventory-employees",
    label: "Сотрудники учета",
    shortLabel: "Получатели",
    hint: "карточки выдачи",
    title: "Бухгалтерия: сотрудники",
    subtitle: "Получатели инвентаря, карточки выдачи и связь с общим справочником сотрудников",
    icon: "E",
    createLabel: "Сверить сотрудников",
  },
  {
    id: "inventory-items",
    label: "Номенклатура",
    shortLabel: "Позиции",
    hint: "каталог позиций",
    title: "Бухгалтерия: номенклатура",
    subtitle: "Каталог позиций, категории, единицы измерения и карточки для выдачи",
    icon: "N",
    createLabel: "Добавить позицию",
  },
  {
    id: "inventory-issue",
    label: "Выдача",
    shortLabel: "Выдача",
    hint: "сотрудникам",
    title: "Бухгалтерия: выдача",
    subtitle: "Оформление выдачи инвентаря сотрудникам и фиксация истории движения",
    icon: "V",
    createLabel: "Создать выдачу",
  },
  {
    id: "inventory-operations",
    label: "Возврат и списание",
    shortLabel: "Операции",
    hint: "возврат и списание",
    title: "Бухгалтерия: возврат и списание",
    subtitle: "Возвраты, списания и история движения предметов по сотрудникам",
    icon: "O",
    createLabel: "Создать операцию",
  },
  {
    id: "inventory-custody",
    label: "Под запись",
    shortLabel: "Под запись",
    hint: "акты и записи",
    title: "Бухгалтерия: под запись",
    subtitle: "Выдача под личную ответственность, акты, закрытие и архив",
    icon: "P",
    createLabel: "Создать акт",
  },
  {
    id: "inventory-ppe",
    label: "СИЗ",
    shortLabel: "СИЗ",
    hint: "карточки и нормы",
    title: "Бухгалтерия: СИЗ",
    subtitle: "Карточки СИЗ, нормы, строки выдачи, возвраты и печатные формы",
    icon: "S",
    createLabel: "Создать карточку СИЗ",
  },
  {
    id: "inventory-ppe-history",
    label: "История СИЗ",
    shortLabel: "История СИЗ",
    hint: "события выдачи",
    title: "СИЗ: история выдачи",
    subtitle: "Выдача, возврат, списание и неисправности без повторяющихся событий",
    icon: "H",
    createLabel: "Обновить историю",
  },
  {
    id: "inventory-ppe-create",
    label: "Создать карточку СИЗ",
    shortLabel: "Создать карточку",
    hint: "конструктор норм",
    title: "СИЗ: создание карточки",
    subtitle: "Нормативный шаблон, пустая карточка, группы, строки и сопоставление номенклатуры",
    icon: "S",
    createLabel: "Создать карточку",
  },
  {
    id: "inventory-reports",
    label: "Отчеты учета",
    shortLabel: "Отчеты",
    hint: "экспорт и печать",
    title: "Бухгалтерия: отчеты",
    subtitle: "Excel/PDF/DOCX, печатные формы и сверка итоговых сумм",
    icon: "R",
    createLabel: "Сформировать отчет",
  },
  {
    id: "inventory-history",
    label: "История",
    shortLabel: "История",
    hint: "журнал операций",
    title: "Бухгалтерия: история",
    subtitle: "Единый журнал выдач, возвратов, списаний, СИЗ и записей под ответственность.",
    icon: "H",
    createLabel: "Обновить журнал",
  },
  {
    id: "inventory-users",
    label: "Права Inventory",
    shortLabel: "Права",
    hint: "RBAC",
    title: "Бухгалтерия: права Inventory",
    subtitle: "Роли и права Inventory поверх текущего RBAC Patrol360.",
    icon: "U",
    createLabel: "Открыть пользователей",
  },
  {
    id: "inventory-system-log",
    label: "Системный журнал",
    shortLabel: "Журнал",
    hint: "аудит",
    title: "Бухгалтерия: системный журнал",
    subtitle: "Аудит изменений, импортов и выгрузок Inventory.",
    icon: "L",
    createLabel: "Открыть аудит",
  },
  {
    id: "inventory-settings",
    label: "Настройки учета",
    shortLabel: "Настройки",
    hint: "нормы и справочники",
    title: "Бухгалтерия: настройки учета",
    subtitle: "Нормы, наборы номенклатуры, причины списания и справочники Inventory",
    icon: "T",
    createLabel: "Открыть настройки",
  },
];

const patrolRouteSeed: RouteDirectoryItem = {
  id: "route-smoke-perimeter",
  name: "Периметр северный",
  territory: "Северный участок",
  status: "Активен",
  description: "Контроль КПП и склада ГСМ для mock/dev проверки обходов.",
  duration: "45 мин",
  distance: "1.8 км",
  periodicity: "Каждая смена",
  points: [
    {
      id: "point-smoke-gate",
      expectedTime: "08:10",
      interval: "10 мин",
      name: "КПП-1",
      description: "Контрольная точка въезда на территорию.",
      instruction: "Поднесите устройство к NFC-метке и проверьте состояние зоны въезда.",
      order: 1,
      requiresPhoto: false,
      status: "Активна",
      tag: "NFC-GATE-01",
      type: "NFC",
      zone: "Въезд",
    },
    {
      id: "point-smoke-fuel",
      expectedTime: "08:25",
      interval: "15 мин",
      name: "Склад ГСМ",
      description: "Контроль оборудования и состояния склада ГСМ.",
      instruction: "Считайте QR-код и осмотрите оборудование на наличие видимых отклонений.",
      order: 2,
      requiresPhoto: false,
      status: "Активна",
      tag: "QR-FUEL-02",
      type: "QR-код",
      zone: "Склад",
    },
  ],
};

const patrolMediaImage =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=";

const patrolMediaVideo = "data:video/mp4;base64,";

export const dashboardMetrics: Metric[] = [];
export const activePatrols: ActivePatrol[] = [
  {
    id: "assignment-smoke-active",
    currentPoint: "КПП-1",
    deviation: "-",
    employee: "Иванов Иван Иванович",
    employeeId: "emp-1",
    eta: "29.06.2026, 08:00",
    plannedAt: "29.06.2026, 08:00",
    plannedAtIso: "2026-06-29T08:00:00Z",
    progress: 0,
    route: patrolRouteSeed.name,
    routeId: patrolRouteSeed.id,
    shift: "День",
    status: "Ожидает",
    zone: patrolRouteSeed.territory,
  },
  {
    id: "assignment-smoke-started",
    currentPoint: "Склад ГСМ",
    deviation: "+5 мин",
    employee: "Петров Петр Петрович",
    employeeId: "emp-2",
    eta: "29.06.2026, 08:15",
    plannedAt: "29.06.2026, 08:15",
    plannedAtIso: "2026-06-29T08:15:00Z",
    progress: 45,
    route: patrolRouteSeed.name,
    routeId: patrolRouteSeed.id,
    shift: "День",
    startedAt: "29.06.2026, 08:21",
    startedAtIso: "2026-06-29T08:21:00Z",
    status: "В пути",
    zone: patrolRouteSeed.territory,
  },
];
export const patrolResults: PatrolResult[] = [
  {
    id: "result-smoke-photo",
    actualAt: "29.06.2026, 08:12",
    assignmentId: "assignment-smoke-completed",
    attachments: [
      {
        id: "attachment-smoke-photo",
        contentType: "image/png",
        createdAt: "29.06.2026, 08:12",
        downloadUrl: patrolMediaImage,
        fileName: "kpp-photo.png",
        sizeBytes: 1024,
      },
      {
        id: "attachment-smoke-video",
        contentType: "video/mp4",
        createdAt: "29.06.2026, 08:13",
        downloadUrl: patrolMediaVideo,
        fileName: "kpp-video.mp4",
        sizeBytes: 2048,
      },
    ],
    chronology: ["План: 29.06.2026, 08:00", "Начато: 29.06.2026, 08:05", "Факт: 29.06.2026, 08:12"],
    comment: "без комментария",
    deviation: "-3 мин",
    employee: "Иванов Иван Иванович",
    employeeId: "emp-1",
    finishedAt: "29.06.2026, 08:40",
    issueType: "нет",
    photos: 2,
    plannedAt: "29.06.2026, 08:15",
    point: "КПП-1",
    pointId: "point-smoke-gate",
    route: patrolRouteSeed.name,
    routeId: patrolRouteSeed.id,
    severity: "-",
    shift: "День",
    source: "mobile",
    startedAt: "29.06.2026, 08:05",
    status: "Подтверждено",
    territory: patrolRouteSeed.territory,
  },
  {
    id: "result-smoke-late",
    actualAt: "29.06.2026, 08:38",
    assignmentId: "assignment-smoke-completed",
    chronology: ["План: 29.06.2026, 08:25", "Факт: 29.06.2026, 08:38", "Замечание: поврежден замок"],
    comment: "Поврежден замок, нужна заявка на ремонт",
    deviation: "+13 мин",
    employee: "Иванов Иван Иванович",
    employeeId: "emp-1",
    finishedAt: "29.06.2026, 08:40",
    issueType: "Повреждение",
    photos: 0,
    plannedAt: "29.06.2026, 08:25",
    point: "Склад ГСМ",
    pointId: "point-smoke-fuel",
    route: patrolRouteSeed.name,
    routeId: patrolRouteSeed.id,
    severity: "Средняя",
    shift: "День",
    source: "mobile",
    startedAt: "29.06.2026, 08:05",
    status: "Просрочено",
    territory: patrolRouteSeed.territory,
  },
];
export const serviceRequests: ServiceRequest[] = [];
export const employees: Employee[] = [];
export const employeeDirectory: EmployeeDirectoryItem[] = accountingEmployeesSeed.map((employee) => ({
  id: employee.id,
  fullName: employee.fullName,
  initials: employee.fullName
    .split(" ")
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? "")
    .join(""),
  personnelNo: employee.personnelNo,
  position: employee.position,
  department: employee.department,
  employeeGroup: employee.employeeGroup,
  birthDate: employee.birthDate ?? "",
  zone: employee.department,
  status: "Активен" as EmployeeDirectoryItem["status"],
  routesDone: 0,
  routesTotal: 0,
  mobileStatus: "Не привязан" as EmployeeDirectoryItem["mobileStatus"],
  lastSeen: "Не входил",
  phone: "",
  hiredAt: employee.hiredAt ?? "",
  brigade: "",
  shift: "День",
  leader: "",
  email: "",
}));
export const siteUsers: SiteUser[] = [];
export const assignableRoutes: RouteOption[] = [
  {
    id: patrolRouteSeed.id,
    controlPoints: patrolRouteSeed.points.filter((point) => point.requiresPhoto).length,
    distance: patrolRouteSeed.distance,
    duration: patrolRouteSeed.duration,
    loadedEmployees: 1,
    name: patrolRouteSeed.name,
    points: patrolRouteSeed.points.length,
    priority: "Обычный",
    requiredEmployees: 2,
    zone: patrolRouteSeed.territory,
  },
];
export const initialAccounts: MobileAccount[] = [];
export const routeDirectory: RouteDirectoryItem[] = [patrolRouteSeed];
export const scheduleCells: ScheduleCell[] = [];
export const securityEvents: string[][] = [];

export const weekDays = ["Пн 11.05", "Вт 12.05", "Ср 13.05", "Чт 14.05", "Пт 15.05", "Сб 16.05", "Вс 17.05"];
